### ISSUE TITLE
Grant access to restricted records by users/groups

### ISSUE THREAD

**Issue by ntarocco** [lnielsen/product-rdm#198]
* Grant access to restricted records/files by user and groups
* Enable sharing of drafts
* Nice to have: explain who has access and why

Related issue: https://github.com/CERNDocumentServer/cds-rdm/issues/109

**Comment by lnielsen** [comment]
We have discovered some UX issues, in that being granted edit access to a draft doesn't grant you access to the request if the record is submitted to a record (if you can select and submit to a community you should also be able to see there request).

![Image](https://github.com/inveniosoftware/product-rdm/assets/1698163/4066ae2b-c1f3-44cf-9a41-233b72900d5b)

![Image](https://github.com/inveniosoftware/product-rdm/assets/1698163/6197f6a7-60b2-4c3c-b98b-bc74065711af)

**Comment by lnielsen** [comment]
@ntarocco @anikachurilova I think probably we can close this issue, and open another one for the missing case.

**Comment by ntarocco** [comment]
> @ntarocco @anikachurilova I think probably we can close this issue, and open another one for the missing case.

Yes, we have created an issue on our side (CDS) and we will create issues in RDM when we will work on these.
